### ISSUE TITLE
MAX_MASSAGE_SIZE? Really folks?

### ISSUE THREAD

**Issue by yomagg** [Azure-Samples/mxchip-iot-devkit-pnp#12]
Just a kind of a silly typo in ``MAX_MASSAGE_SIZE``, right? This typo makes me smile. It is in files generated by Digital Twin Code Generator, e.g., ``screen_interface.c`` or ``settings_interface.c`` so I guess the tool is a culprit and the way to fix it. 

``MAX_MESSAGE_SIZE 256``

would look much better.

**Comment by IvanJobs** [comment]
@yomagg  Thanks for your feedback and I think this typo will be fixed in the future.

**Comment by JerryYangKai** [comment]
Fix it.

**Comment by IvanJobs** [comment]
fixed to close.
