### ISSUE TITLE
I can't register my device

### ISSUE THREAD

**Issue by davidamayuelas** [Azure-Samples/mxchip-iot-devkit-pnp#15]
Stays in registering mode without changing the retry number (always 1)

**Comment by IvanJobs** [comment]
@davidamayuelas Thanks for your feedback, and please provide more info for easier trouble-shooting.

**Comment by davidamayuelas** [comment]
Arduino 0.2.29
VSCode 1.43.0
The problem appears when i upload the wifi settings and the MxChip restart

**Comment by JerryYangKai** [comment]
Hi @davidamayuelas, can you show us the log in serial port?
