### ISSUE TITLE
#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (C:\Work\mxchips\mxchip-iot-devkit-pnp\Device\main.ino).

### ISSUE THREAD

**Issue by balakreshnan** [Azure-Samples/mxchip-iot-devkit-pnp#16]
#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (C:\Work\mxchips\mxchip-iot-devkit-pnp\Device\main.ino). Don't know what to include in the path. WIth the above error here is another one. 
cannot open source file "digitaltwin_device_client_ll.h" (dependency of "src/mxchip_iot_devkit/pnp_device.h")

Happens in Visual Code 1.4 version.

**Comment by JerryYangKai** [comment]
Hi @balakreshnan, I think your devkit sdk version may be 1.6.X. This sample needs 1.9.11.

**Comment by balakreshnan** [comment]
How do I update to version 1.9.11?
________________________________

**Comment by balakreshnan** [comment]
I also tried to use additional url and https://raw.githubusercontent.com/VSChina/azureiotdevkit_tools/master/package_azureboard_index.json doesn't have version 1.9.11
raw.githubusercontent.com<https://raw.githubusercontent.com/VSChina/azureiotdevkit_tools/master/package_azureboard_index.json>
{ "packages": [ { "name": "AZ3166", "maintainer": "Microsoft Developer", "websiteURL": "https://microsoft.github.io/azure-iot-developer-kit/", "email": "aziotdevkit ...
raw.githubusercontent.com

________________________________

**Comment by JerryYangKai** [comment]
@balakreshnan  Hi, this is our tutorials 
https://docs.microsoft.com/en-us/samples/azure-samples/mxchip-iot-devkit-pnp/sample/
The right url is 
https://raw.githubusercontent.com/vschina/azureiotdevkit_tools/pnp/package_mxchip_board_preview_index.json
If you still can not find 1.9.11. Pls del all files in C:\Users\<your_name>\AppData\Local\Arduino15 to clean cache.
