### ISSUE TITLE
MXChip disconnects after 6h from IoT Central

### ISSUE THREAD

**Issue by asergaz** [Azure-Samples/mxchip-iot-devkit-pnp#8]
Looks like the SAS token is not renewed and the device disconnects after 6h.

You can reproduce it easily if you let your device connected to IoT Central (preview) app for more than 6h.

**Comment by rido-min** [comment]
+@liydu to investigate

**Comment by asergaz** [comment]
@liydu what's the status? Thanks

**Comment by JerryYangKai** [comment]
@asergaz  https://github.com/Azure/azure-iot-sdk-c/issues/1406#issuecomment-577818997 We will fixed it in next released.

**Comment by JerryYangKai** [comment]
@asergaz  Hi, this is happening because the SAS token expires every hour. The device will reconnect and refresh the token. We have fixed it.

**Comment by asergaz** [comment]
@JerryYangKai in my case it disconnects every 6hours. I don't believe the issue is the same... can you confirm?

**Comment by JerryYangKai** [comment]
@asergaz I have not reproed your issue. It is difficult for me to test because it needs six hours. I tried three times these days and my mxchip still working. Can you paste your log in your serrial port?

**Comment by asergaz** [comment]
@JerryYangKai it should be easy to repro... just leave your device connected through the night. How would I provide the logs? Do we have a documentation to output the needed information while the repro is done? Thanks.

**Comment by JerryYangKai** [comment]
@asergaz  You can monitor data sent over this serial connection using the VS Code Serial Monitor, available from the command palette by selecting Arduino: Open Serial Monitor. The board will send logging information over this port in addition to the data you send.

I think it may be caused by weak wi-fi. I have left my devkit for a night and it still working when i wake up.

**Comment by asergaz** [comment]
Thanks for the details @JerryYangKai I will try to collect the logs when it fails. Fyi: my board is next to the Wifi router :)!
