### ISSUE TITLE
Custom template MXChip problems + commands not working

### ISSUE THREAD

**Issue by SpaBruis** [Azure-Samples/mxchip-iot-devkit-pnp#9]
When i try to connect the MXChip to a custom interface (with the same telemetry names, but without all the other interfaces) it doesn't work:
![afbeelding](https://user-images.githubusercontent.com/55592439/75016618-aabe3180-548b-11ea-93fb-dae24c1d75cb.png)

![afbeelding](https://user-images.githubusercontent.com/55592439/75016652-c1648880-548b-11ea-8886-53d0add2e362.png)

The commands in the MXChip template don't work either.

Please provide some feedback, thanks!

**Comment by SpaBruis** [comment]
The telemetry is sent correctly (i suppose): 
![afbeelding](https://user-images.githubusercontent.com/55592439/75017621-aeeb4e80-548d-11ea-99d1-73ae4ecb3377.png)

**Comment by rido-min** [comment]
are you using the same device code implementation? I'd suggest to check if the InterfaceInstanceNames used in your code match the instance names in the DCM.

**Comment by SpaBruis** [comment]
Hello Ricardo, the interface name was indeed the problem, thanks! Although, the commands are still not working:
![afbeelding](https://user-images.githubusercontent.com/55592439/75162412-cfc9d300-571d-11ea-9f1c-7032027300df.png)
This is with the built-in device template. I am using the latest firmware from this git repo.

Thanks in advance!

**Comment by JerryYangKai** [comment]
Hi @SpaBruis, I will try to repro this issue and fix it soon.

**Comment by SpaBruis** [comment]
@JerryYangKai Great! Let me know when you fixed it, thanks in advance!

**Comment by SpaBruis** [comment]
Hi @JerryYangKai are there any updates?

**Comment by JerryYangKai** [comment]
@SpaBruis Hi, I tried to repro your issue and I still can not repro it. The commands works well in my device. I need more information about your issue. 
Frist is your sensor dashboard,  I know your device is sending telemetry and I need to confirm whether your IoT central have received it like this.
![image](https://user-images.githubusercontent.com/53805504/76048292-4ed1cd80-5fa0-11ea-8412-55fd8883c191.png)
Second is your log in your serial port, the log should be this when you trigger the commands.
![image](https://user-images.githubusercontent.com/53805504/76048387-a53f0c00-5fa0-11ea-9350-fef3d14e3566.png)

**Comment by SpaBruis** [comment]
Hi Jerry, I created a new IoT Central instance and it's working fine now. I'm sorry for the nuisance. Thanks for your time and effort!
